### ISSUE TITLE
Crash when launched from the status bar

### ISSUE THREAD

**Issue by RiccardoPP** [loiccoyle/rofi-nordvpn#1]
Hello, and thanks for this code.

If I launch the script via a terminal everything is ok.

If I launch the script by clicking in the status bar module (WayBar, configured as your Polybar example) it crashes after "cities" or "countries" selection (the other voices of the menu are ok).

I've tried to debug it without success. Any ideas?

Thanks

**Comment by loiccoyle** [comment]
hmm weird, I suspect it is due to the way `waybar` runs commands, there must be some quirk with the `--generate-bash-completion` option or something.

Can you try the `fix/status_bar` branch and see if it helps?

**Comment by RiccardoPP** [comment]
Thanks, that branch works! I'll try it more deeply and let you know if I'll see other issues.

**Comment by Shringe** [comment]
I had the same issue with launching through Polybar, and i3 keybinding; it only crashes when Nordvpn is already connected. The `fix/status_bar` branch fixes this issue. Is there any reason why it is not merged into main branch?

**Comment by loiccoyle** [comment]
Thanks for the info, I didn't realise this issue affects polybar too. The solution I used in `fix/status_bar` isn't great and felt a bit janky but it's better than nothing, I'll merge it in `main`.

EDIT: done in [`a521459`](https://github.com/loiccoyle/rofi-nordvpn/commit/a5214590530a40b9bcbac325723197fcf0b99b41)
